// Mocks generated by Mockito 5.3.2 from annotations
// in my_to_day/feature/diary/service/diary_local_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_to_day/feature/diary/service/diary_local_service.dart'
    as _i2;
import 'package:my_to_day/model/data/diary_data.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DiaryLocalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiaryLocalService extends _i1.Mock implements _i2.DiaryLocalService {
  @override
  List<_i3.DiaryData> getAllDiaryData() => (super.noSuchMethod(
        Invocation.method(
          #getAllDiaryData,
          [],
        ),
        returnValue: <_i3.DiaryData>[],
        returnValueForMissingStub: <_i3.DiaryData>[],
      ) as List<_i3.DiaryData>);
  @override
  _i4.Future<void> setDiaryData({required _i3.DiaryData? diaryData}) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDiaryData,
          [],
          {#diaryData: diaryData},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> editDiaryData({required _i3.DiaryData? diaryData}) =>
      (super.noSuchMethod(
        Invocation.method(
          #editDiaryData,
          [],
          {#diaryData: diaryData},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> deleteDiaryData({required dynamic key}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDiaryData,
          [],
          {#key: key},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
