name: my_to_day
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  intl: ^0.17.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  provider: ^6.0.3
  share_plus: ^4.0.7
  image_picker: ^0.8.5+3
  card_swiper: ^2.0.4
  insta_image_viewer: ^0.0.1+3
  table_calendar: ^3.0.6
  google_maps_flutter: ^2.1.10




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  hive_generator: ^1.1.2
  geolocator: ^9.0.1

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AppleSDGothicNeo
      fonts:

        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoR.otf
          weight: 400
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoM.otf
          weight: 500
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoSB.otf
          weight: 600
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoB.otf
          weight: 700
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoEB.otf
          weight: 800

    - family: SFUIDisplay
      fonts:

        - asset: assets/fonts/SFUIDisplay/sf-ui-display-medium.otf
          weight: 500
        - asset: assets/fonts/SFUIDisplay/sf-ui-display-semibold.otf
          weight: 600
        - asset: assets/fonts/SFUIDisplay/sf-ui-display-bold.otf
          weight: 700

    - family: SFProDisplay
      fonts:

        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Black.otf
          weight: 800

    - family: SFProText
      fonts:

        - asset: assets/fonts/SFProText/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProText/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProText/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFProText/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SFProText/SF-Pro-Text-Black.otf
          weight: 800

    - family: Arial
      fonts:
        - asset: assets/fonts/Arial/Arial-Regular.ttf
          weight: 400
        - asset: assets/fonts/Arial/Arial-Medium.ttf
          weight: 500
        - asset: assets/fonts/Arial/Arial-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.otf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
