name: Flutter CI

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1.5.1
        with:
          flutter-version: "3.7.7"

      - name: Pub Get Packages
        run: | 
          flutter pub get

      - name: Test
        run: |
          flutter test
